package com.sagar.passwordmanager.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.sagar.passwordmanager.persistent.Account;
import com.sagar.passwordmanager.persistent.User;

/**
 * Class _Provider was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Provider extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<List<Account>> ACCOUNTS = Property.create("accounts", List.class);
    public static final Property<User> USER = Property.create("user", User.class);

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToAccounts(Account obj) {
        addToManyTarget("accounts", obj, true);
    }
    public void removeFromAccounts(Account obj) {
        removeToManyTarget("accounts", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Account> getAccounts() {
        return (List<Account>)readProperty("accounts");
    }


    public void setUser(User user) {
        setToOneTarget("user", user, true);
    }

    public User getUser() {
        return (User)readProperty("user");
    }


}
