package com.sagar.passwordmanager.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.sagar.passwordmanager.persistent.Provider;

/**
 * Class _User was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _User extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String UID_PK_COLUMN = "UID";

    public static final Property<String> MASTER_PASSWORD = Property.create("masterPassword", String.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<List<Provider>> PROVIDERS = Property.create("providers", List.class);

    public void setMasterPassword(String masterPassword) {
        writeProperty("masterPassword", masterPassword);
    }
    public String getMasterPassword() {
        return (String)readProperty("masterPassword");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToProviders(Provider obj) {
        addToManyTarget("providers", obj, true);
    }
    public void removeFromProviders(Provider obj) {
        removeToManyTarget("providers", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Provider> getProviders() {
        return (List<Provider>)readProperty("providers");
    }


}
